#!/bin/sh

set -e

PREREQ="cryptroot"
CONF=/etc/ykluks.conf

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/ykchalresp
cp /usr/share/yubikey-luks/ykluks-keyscript "${DESTDIR}/sbin/ykluks-keyscript"
if [ -f $CONF ]; then
    cp $CONF "${DESTDIR}/etc/${CONF}"
exit 0
