#! /bin/sh

set -e

PREREQ=""


message()
{
    if [ -x /bin/plymouth ] && plymouth --ping; then
        plymouth message --text="$@"
    else
        echo "$@" >&2
    fi
    return 0
}

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Propagate update from initrd to rootfs on disk
if [ -f /tmp/ykluks.updated ]; then
	mount -o remount -w /dev/mapper/ubuntu--vg-root /root
	mv root/etc/ykluks.conf /root/etc/ykluks.conf.used
	mount -o remount -r /dev/mapper/ubuntu--vg-root /root
fi

message "Welcome!"

exit 0
