#! /bin/sh

set -e

PREREQ=""


message()
{
    if [ -x /bin/plymouth ] && plymouth --ping; then
        plymouth message --text="$@"
    else
        echo "$@" >&2
    fi
    return 0
}

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

message "Welcome!"

exit 0
